<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-07 00:43
=======
# Generated by Django 4.0.3 on 2023-04-09 13:27
>>>>>>> 5357af978d8fc2f4f806b0e7f30ab53a00305135

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
<<<<<<< HEAD
                ('created', models.DateField(auto_now_add=True)),
=======
                ('created', models.DateTimeField(auto_now_add=True)),
>>>>>>> 5357af978d8fc2f4f806b0e7f30ab53a00305135
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
